### PR TITLE
feat: NestJS v9 Compatibility

### PR DESCRIPTION
**Pull request by alexb-uk**
I was unable to test this locally as `npm link` appears to break NestJS dependency injection 😢 

However:
- It builds without TypeScript errors / warnings
- All tests pass
- I have been running `@narando/nest-xray` v2.0.0 with the following NestJS v9 packages without issue. Albeit with having to use `npm install --legacy-peer-deps` to get around the upstream version clash.

```json
"dependencies": {
    "@narando/nest-xray": "^2.0.0",
    "@narando/nest-axios-interceptor": "^2.2.0",
    "@nestjs/axios": "^0.1.0",
    "@nestjs/common": "^9.0.7",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.7",
    "@nestjs/platform-express": "^9.0.7",
    "@nestjs/swagger": "^6.0.3",
    "@nestjs/terminus": "^9.1.0",
    ...
    "axios": "^0.27.2",
    ...
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.1",
    "@nestjs/testing": "^9.0.7",
```
_This is on Node v16._

If there are any known issues with v9 I'm happy to try and resolve, although I'm very new to NestJS generally speaking.

Thanks

### CODE REVIEW

**Comment by alexb-uk** [comment]
Thought I would give NPM workspaces a shot but no joy..... get the same error as when using `npm link`:

```
Error: Nest can't resolve dependencies of the XyzService (?). Please make sure that the argument HttpService at index [0] is available in the XyzModule context.

Potential solutions:
- If HttpService is a provider, is it part of the current XyzModule?
- If HttpService is exported from a separate @Module, is that module imported within XyzModule?
  @Module({
    imports: [ /* the Module containing HttpService */ ]
  })
```

**Comment by alexb-uk** [comment]
Hi, anything I can do to help get this merged?

**Review by apricote — CHANGES_REQUESTED** [review]
Looks good in general, this should make it compatible with NestJS 9.

Can you please change the version ranges to use the exact version for `dependencies` and `devDependencies`? e.g. change from `^2.2.0` to `2.2.0`.

Also, the readme currently states that nest-xray v2 is compatible with NestJS 8, maye you can also add NestJS 9 to that list?

**Comment by alexb-uk** [comment]
> Looks good in general, this should make it compatible with NestJS 9.
> 
> Can you please change the version ranges to use the exact version for `dependencies` and `devDependencies`? e.g. change from `^2.2.0` to `2.2.0`.
> 
> Also, the readme currently states that nest-xray v2 is compatible with NestJS 8, maye you can also add NestJS 9 to that list?

@apricote Done and resolved merged conflicts.
Please could you re-review and double check I got them all.

Note: I've bumped up the `aws-xray-sdk` package to latest version. We've been using this in a number of projects without any issues.

Thanks again

**Comment by apricote** [comment]
Thanks a lot for the contribution @alexb-uk!

**Comment by apricote** [comment]
This was released as `2.1.0`

**Pull request merged**
