### PR TITLE
feat(ci): add automatic changelog and releases on npm

### PR DESCRIPTION
**Pull request by MarcMogdanz**
This enables an automatic generated changelog as well automatic publishing to npm.

@apricote I think you need to add  `npm_token` to the GitHub secrets

### CODE REVIEW

**Comment by apricote** [comment]
I added a secret with the npm token.

**Comment by MarcMogdanz** [comment]
Is node `12.x` fine? current LTS are `10` and `12` but I'm not sure if there would be some backwards compability issue

**Comment by apricote** [comment]
Node `12.x` is fine, should be no compatability issues during build time. `CI` pipeline is already executed in `10.x`, `12.x`, and `13.x` and should flag any issues.

**Comment by apricote** [comment]
https://github.com/narando/nest-xray/commit/fb7b7e46989e1426ff01b26a79e440fe953c8140/checks?check_suite_id=402656062

Its missing `npm ci`. Can you create a new PR for that @MarcMogdanz?

**Comment by MarcMogdanz** [comment]
Done in #3

**Pull request merged**
